name: meinErsterWorkflow

on: push
pull_request

jobs:
  changed-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Abschied 
        run: "Bye Bye!"
      - name: meinErsterStep
        run: echo "Hallo Welt!"

  zweiter-job:   
    runs-on: ubuntu-latest
    needs: changed-job
    steps:
      - name: Datum anzeigen 
        run: date
